In [20]:
import pandas as pd
import numpy as np
import mlflow
import mlflow.sklearn
from mlflow.models.signature import infer_signature
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [21]:
import mlflow

# set tracking server uri for logging
mlflow.set_tracking_uri(uri="http://127.0.0.1:5000")

#create a new MLflow Experiment
mlflow.set_experiment("MLflow for Fraud detection")

<Experiment: artifact_location='mlflow-artifacts:/668097690514392710', creation_time=1719263205613, experiment_id='668097690514392710', last_update_time=1719263205613, lifecycle_stage='active', name='MLflow for Fraud detection', tags={}>

In [22]:
# Load the datasets
fraud_df = pd.read_csv('../data/old/Fraud_Data.csv')
credit_df = pd.read_csv('../data/old/creditcard.csv')

In [23]:
fraud_df

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,7.327584e+08,0
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,3.503114e+08,0
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,2.621474e+09,1
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,3.840542e+09,0
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,4.155831e+08,0
...,...,...,...,...,...,...,...,...,...,...,...
151107,345170,2015-01-27 03:03:34,2015-03-29 00:30:47,43,XPSKTWGPWINLR,SEO,Chrome,M,28,3.451155e+09,1
151108,274471,2015-05-15 17:43:29,2015-05-26 12:24:39,35,LYSFABUCPCGBA,SEO,Safari,M,32,2.439047e+09,0
151109,368416,2015-03-03 23:07:31,2015-05-20 07:07:47,40,MEQHCSJUBRBFE,SEO,IE,F,26,2.748471e+09,0
151110,207709,2015-07-09 20:06:07,2015-09-07 09:34:46,46,CMCXFGRHYSTVJ,SEO,Chrome,M,37,3.601175e+09,0
151111,138208,2015-06-10 07:02:20,2015-07-21 02:03:53,20,ZINIADFCLHYPG,Direct,IE,M,38,4.103825e+09,0

In [24]:
import category_encoders as ce
encoder= ce.OrdinalEncoder(cols=['source'],return_df=True,
                           mapping=[{'col':'source',
'mapping':{'None':0,'SEO':1,'Ads':2,'Direct':3}}])

In [25]:
fraud_df = encoder.fit_transform(fraud_df)

In [26]:
encoder= ce.OrdinalEncoder(cols=['browser'],return_df=True,
                           mapping=[{'col':'browser',
'mapping':{'None':0,'Chrome':1,'IE':2,'Safari':3,'FireFox':4,'Opera':5}}])

In [27]:
fraud_df = encoder.fit_transform(fraud_df)

In [28]:
encoder= ce.OrdinalEncoder(cols=['sex'],return_df=True,
                           mapping=[{'col':'sex',
'mapping':{'F':0,'M':1}}])

In [29]:
fraud_df = encoder.fit_transform(fraud_df)

In [30]:
fraud_df

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,1,1,1,39,7.327584e+08,0
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,2,1,0,53,3.503114e+08,0
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,1,5,1,53,2.621474e+09,1
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,1,3,1,41,3.840542e+09,0
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,2,3,1,45,4.155831e+08,0
...,...,...,...,...,...,...,...,...,...,...,...
151107,345170,2015-01-27 03:03:34,2015-03-29 00:30:47,43,XPSKTWGPWINLR,1,1,1,28,3.451155e+09,1
151108,274471,2015-05-15 17:43:29,2015-05-26 12:24:39,35,LYSFABUCPCGBA,1,3,1,32,2.439047e+09,0
151109,368416,2015-03-03 23:07:31,2015-05-20 07:07:47,40,MEQHCSJUBRBFE,1,2,0,26,2.748471e+09,0
151110,207709,2015-07-09 20:06:07,2015-09-07 09:34:46,46,CMCXFGRHYSTVJ,1,1,1,37,3.601175e+09,0
151111,138208,2015-06-10 07:02:20,2015-07-21 02:03:53,20,ZINIADFCLHYPG,3,2,1,38,4.103825e+09,0

In [31]:
fraud_df['signup_time'] = pd.to_datetime(fraud_df['signup_time'])
fraud_df['purchase_time'] = pd.to_datetime(fraud_df['purchase_time'])

fraud_df['signup_hour'] = fraud_df['signup_time'].apply(lambda x: x.hour)
fraud_df['signup_day'] = fraud_df['signup_time'].apply(lambda x: x.day)
fraud_df['purchase_hour'] = fraud_df['purchase_time'].apply(lambda x: x.hour)
fraud_df['purchase_day'] = fraud_df['purchase_time'].apply(lambda x: x.day)

fraud_df = fraud_df.drop(columns=['signup_time', 'purchase_time', 'device_id'])

In [32]:
fraud_df

,user_id,purchase_value,source,browser,sex,age,ip_address,class,signup_hour,signup_day,purchase_hour,purchase_day
0,22058,34,1,1,1,39,7.327584e+08,0,22,24,2,18
1,333320,16,2,1,0,53,3.503114e+08,0,20,7,1,8
2,1359,15,1,5,1,53,2.621474e+09,1,18,1,18,1
3,150084,44,1,3,1,41,3.840542e+09,0,21,28,13,4
4,221365,39,2,3,1,45,4.155831e+08,0,7,21,18,9
...,...,...,...,...,...,...,...,...,...,...,...,...
151107,345170,43,1,1,1,28,3.451155e+09,1,3,27,0,29
151108,274471,35,1,3,1,32,2.439047e+09,0,17,15,12,26
151109,368416,40,1,2,0,26,2.748471e+09,0,23,3,7,20
151110,207709,46,1,1,1,37,3.601175e+09,0,20,9,9,7
151111,138208,20,3,2,1,38,4.103825e+09,0,7,10,2,21

In [33]:
from sklearn.model_selection import train_test_split
fraud_x = fraud_df.drop(columns=['class'])
fraud_y = fraud_df['class']

creditcard_x = credit_df.drop(columns=['Class'])
creditcard_y = credit_df['Class']

fraud_x_train, fraud_x_test, fraud_y_train, fraud_y_test = train_test_split(fraud_x, fraud_y, test_size=0.3, random_state=42)
creditcard_x_train, creditcard_x_test, creditcard_y_train, creditcard_y_test = train_test_split(creditcard_x, creditcard_y, test_size=0.3, random_state=42)

In [34]:
# Define preprocessing for numerical and categorical features
numeric_features = ['purchase_value', 'age']
categorical_features = ['source', 'browser', 'sex', 'signup_hour', 'signup_day', 'purchase_hour', 'purchase_day']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

In [35]:

# Model Selection
models = {
    'LogisticRegression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'MLP': MLPClassifier()
}

# Function to train and evaluate models for fraud data
def train_evaluate_model_fraud(model_name, model, x_train, x_test, y_train, y_test):
    # Create a pipeline with preprocessing and model
    model_pipeline = Pipeline(steps=[('preprocessor', preprocessor), # Change the variable name to model_pipeline
                               ('classifier', model)])
    # Train the model
    model_pipeline.fit(x_train, y_train)

    # Make predictions
    y_pred = model_pipeline.predict(x_test) # Use the new variable name here as well

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Infer model signature
    signature = mlflow.models.infer_signature(x_train, y_pred) # Call infer_signature from mlflow
    #signature = infer_signature(x_train, y_pred)
    # log metrics and model with MLflow
    with mlflow.start_run(run_name=model_name):
        mlflow.log_param("model", model_name)
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)
        mlflow.set_tag("Training Info", "All models for Fraud detection")
        model_info = mlflow.sklearn.log_model(
            sk_model=model_pipeline, # And here
            artifact_path="fraud_model",
            signature=signature,
            input_example=x_train,
            registered_model_name=f"{model_name}_fraud_detection",
        )
    return{
        'model': model_name,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1
    }

# Function to train and evaluate models for credit card data
def train_evaluate_model_credit(model_name, model, x_train, x_test, y_train, y_test):
    # Create a pipeline with preprocessing and model
    model_pipeline = Pipeline(steps=[('classifier', model)]) # Change the variable name to model_pipeline
                               
    # Train the model
    model_pipeline.fit(x_train, y_train)
    
    # Make predictions
    y_pred = model_pipeline.predict(x_test) # Use the new variable name here as well
    
    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    # Infer model signature
    signature = mlflow.models.infer_signature(x_train, y_pred) # Call infer_signature from mlflow
   
    # log metrics and model with MLflow
    with mlflow.start_run(run_name=model_name):
        mlflow.log_param("model", model_name)
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)
        mlflow.set_tag("Training Info", "All models for Credit Card Fraud detection")
        model_info = mlflow.sklearn.log_model(
            sk_model=model_pipeline, # And here
            artifact_path="creditcard_model",
            signature=signature,
            input_example=x_train,
            registered_model_name=f"{model_name}_creditcard_detection",
        )
    return{
        'model': model_name,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1
    }

In [36]:
fraud_x_train, fraud_x_test, fraud_y_train, fraud_y_test = train_test_split(fraud_x, fraud_y, test_size=0.3, random_state=42)
creditcard_x_train, creditcard_x_test, creditcard_y_train, creditcard_y_test = train_test_split(creditcard_x, creditcard_y, test_size=0.3, random_state=42)

# Train and evaluate models on fraud data

fraud_results = []
for model_name, model in models.items():
    fraud_results.append(train_evaluate_model_fraud(model_name, model, fraud_x_train, fraud_x_test, fraud_y_train, fraud_y_test))
creditcard_results = []
for model_name, model in models.items():
    creditcard_results.append(train_evaluate_model_credit(model_name, model, creditcard_x_train, creditcard_x_test, creditcard_y_train, creditcard_y_test))

# Display results
fraud_results_df = pd.DataFrame(fraud_results)
creditcard_results_df = pd.DataFrame(creditcard_results)

print("Fraud Data Results:\n", fraud_results_df)
print("Credit Card Data Results:\n", creditcard_results_df)

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\hp\anaconda3\Lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Successfully registered model 'LogisticRegression_fraud_detection'.
2024/06/27 21:20:04 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LogisticRegression_fraud_detection, version 1
Created version '1' of model 'LogisticRegression_fraud_detection'.
c:\Users\hp\anaconda3\Lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Successfully registered model 'Decision Tree_fraud_detection'.
2024/06/27 21:20:21 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Decision Tree_fraud_detection, version 1
Created version '1' of model 'Decision Tree_fraud_detection'.
c:\Users\hp\anaconda3\Lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Successfully registered model 'Random Forest_fraud_detection'.
2024/06/27 21:23:01 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Random Forest_fraud_detection, version 1
Created version '1' of model 'Random Forest_fraud_detection'.
c:\Users\hp\anaconda3\Lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Successfully registered model 'Gradient Boosting_fraud_detection'.
2024/06/27 21:23:20 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Gradient Boosting_fraud_detection, version 1
Created version '1' of model 'Gradient Boosting_fraud_detection'.
c:\Users\hp\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\hp\anaconda3\Lib\site-packages\mlflow\types\utils.py:394: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
Successfully registered model 'MLP_fraud_detection'.
2024/06/27 21:25:41 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: MLP_fraud_detection, version 1
Created version '1' of model 'MLP_fraud_detection'.
c:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
Successfully registered model 'LogisticRegression_creditcard_detection'.
2024/06/27 21:26:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LogisticRegression_creditcard_detection, version 1
Created version '1' of model 'LogisticRegression_creditcard_detection'.
Successfully registered model 'Decision Tree_creditcard_detection'.
2024/06/27 21:26:46 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Decision Tree_creditcard_detection, version 1
Created version '1' of model 'Decision Tree_creditcard_detection'.
Successfully registered model 'Random Forest_creditcard_detection'.
2024/06/27 21:31:35 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Random Forest_creditcard_detection, version 1
Created version '1' of model 'Random Forest_creditcard_detection'.
Successfully registered model 'Gradient Boosting_creditcard_detection'.
2024/06/27 21:39:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Gradient Boosting_creditcard_detection, version 1
Created version '1' of model 'Gradient Boosting_creditcard_detection'.
Successfully registered model 'MLP_creditcard_detection'.
2024/06/27 21:40:37 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: MLP_creditcard_detection, version 1
Created version '1' of model 'MLP_creditcard_detection'.

Fraud Data Results:
                 model  accuracy  precision    recall  f1_score
0  LogisticRegression  0.906979   0.000000  0.000000  0.000000
1       Decision Tree  0.914038   0.536052  0.564145  0.549740
2       Random Forest  0.955177   0.955778  0.543277  0.692773
3   Gradient Boosting  0.945891   0.817266  0.538772  0.649421
4                 MLP  0.931641   0.657731  0.552763  0.600696
Credit Card Data Results:
                 model  accuracy  precision    recall  f1_score
0  LogisticRegression  0.999134   0.771930  0.647059  0.704000
1       Decision Tree  0.999263   0.735484  0.838235  0.783505
2       Random Forest  0.999590   0.924370  0.808824  0.862745
3   Gradient Boosting  0.998584   0.894737  0.125000  0.219355
4                 MLP  0.997226   0.271493  0.441176  0.336134